spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
    pathmatch:
      matching-strategy: ant-path-matcher
    
  datasource:
    username: test_user
    password: test_user12!
    mapper-locations: classpath:/mapper/**/*.xml
    jdbc-url: jdbc:mysql://192.168.0.13:3306/edu?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driver: com.mysql.cj.jdbc.Driver
    
  thymeleaf:
     cache : false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  file:
    upload-location: C:\workspace\BTONE_LibMgmt\src\main\resources\static\img
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml

file:
  upload-location : /src/main/webapp/img/