spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
    pathmatch:
      matching-strategy: ant-path-matcher
    
  datasource:
    username: test_user
    password: test_user12!
    mapper-locations: classpath:/mapper/**/*.xml
    jdbc-url: jdbc:mysql://192.168.0.152:3306/edu?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driver: com.mysql.cj.jdbc.Driver
    
  thymeleaf:
     prefix : classpath:templates/html
     suffix : .html
     cache : false
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml